name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'  # Trigger solo sui tag come v1.0, v1.1, ecc.
  workflow_dispatch:  # Possibilità di eseguirlo manualmente

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller pymupdf PyPDF2[full]

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed estrai_pagine_pdf.py

    - name: Rename EXE with version
      run: |
        $version = "${{ github.ref_name }}"
        Rename-Item -Path "dist/estrai_pagine_pdf.exe" -NewName "PDF-Sifter_$version.exe"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/PDF-Sifter_*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
